---
- name: restart firewalld
  service: name=firewalld state=restarted
  when:
    - docker_skip_tasks is not defined or not docker_skip_tasks
    - firewall_skip_tasks is not defined or not firewall_skip_tasks
