---

- hosts: app-servers
  become: yes
  roles:
    - set-vars
    - create-wiki-wrapper
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
      when: docker_skip_tasks is not defined or not docker_skip_tasks

- hosts: parsoid-servers
  become: yes
  roles:
    - set-vars
    - parsoid-settings
