---
list:
#
# Extensions loaded with wfLoadExtension()
#
- name: AJAXPoll
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/AJAXPoll.git
  version: "{{ mediawiki_default_branch }}"
- name: AntiSpoof
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/AntiSpoof.git
  version: "{{ mediawiki_default_branch }}"
# This is either old, or a plugin. Check documentation for CentralAuth
# - name: AntiSpoofForCentralAuth
#   repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/AntiSpoofForCentralAuth.git
#   version: "{{ mediawiki_default_branch }}"
- name: CategoryTree
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CategoryTree.git
  # CategoryTree didn't convert to extension registration until 1_28
  version: "{{ mediawiki_default_branch }}"

# - name: CentralAuth
#   repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CentralAuth.git
#   version: "{{ mediawiki_default_branch }}"

- name: CheckUser
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CheckUser.git
  version: "{{ mediawiki_default_branch }}"
- name: ConfirmEdit
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ConfirmEdit.git
  version: "{{ mediawiki_default_branch }}"
  config: |
    # QuestyCaptcha is a plugin for ConfirmEdit, not a separate repo
    require_once( "$IP/extensions/ConfirmEdit/QuestyCaptcha.php");
    $wgCaptchaClass = 'QuestyCaptcha';
    #Generate the array with all champions
    $myChampArray = array("Aatrox","Ahri","Akali","Alistar","Amumu","Anivia","Annie","Ashe","Azir","Bard",
    "Blitzcrank","Brand","Braum","Caitlyn","Cassiopeia","Cho'Gath","Corki","Darius","Diana","Dr. Mundo",
    "Draven","Ekko","Elise","Evelynn","Ezreal","Fiddlesticks","Fiora","Fizz","Galio","Gangplank",
    "Garen","Gnar","Gragas","Graves","Hecarim","Heimerdinger","Illaoi","Irelia","Janna","Jarvan IV",
    "Jax","Jayce","Jhin","Jinx","Kalista","Karma","Karthus","Kassadin","Katarina","Kayle",
    "Kennen","Kha'Zix","Kindred","Kog'Maw","LeBlanc","Lee Sin","Leona","Lissandra","Lucian","Lulu",
    "Lux","Malphite","Malzahar","Maokai","REL1_27 Yi","Miss Fortune","Mordekaiser","Morgana","Nami","Nasus",
    "Nautilus","Nidalee","Nocturne","Nunu","Olaf","Orianna","Pantheon","Poppy","Quinn","Rammus",
    "Rek'Sai","Renekton","Rengar","Riven","Rumble","Ryze","Sejuani","Shaco","Shen","Shyvana",
    "Singed","Sion","Sivir","Skarner","Sona","Soraka","Swain","Syndra","Tahm Kench","Talon",
    "Taric","Teemo","Thresh","Tristana","Trundle","Tryndamere","Twisted Fate","Twitch","Udyr","Urgot",
    "Varus","Vayne","Veigar","Vel'Koz","Vi","Viktor","Vladimir","Volibear","Warwick","Wukong",
    "Xerath","Xin Zhao","Yasuo","Yorick","Zac","Zed","Ziggs","Zilean","Zyra");

    #Get 8 random Champions and put them in an array
    $myChampNumbers= range( 0, count( $myChampArray ) - 1 );
    shuffle( $myChampNumbers );
    $myRandChampNumbers = array_slice( $myChampNumbers, 0, 8 );
    $myRandChampions = array(
            $myChampArray[$myRandChampNumbers[0]],
            $myChampArray[$myRandChampNumbers[1]],
            $myChampArray[$myRandChampNumbers[2]],
            $myChampArray[$myRandChampNumbers[3]],
            $myChampArray[$myRandChampNumbers[4]],
            $myChampArray[$myRandChampNumbers[5]],
            $myChampArray[$myRandChampNumbers[6]],
            $myChampArray[$myRandChampNumbers[7]]
    );

    # Pick a random location in these 8 champs
    $myChallengeIndex = rand( 0, 7 );
    # Let's use words to describe the position, just to make it a bit more complicated
    $myChallengePositions = array ( 'first', 'second', 'third', 'fourth', 'fifth', 'sixth', 'seventh', 'eighth' );
    $myChallengePositionName = $myChallengePositions[$myChallengeIndex];

    $myChallengeQuestion = "Please enter the " . $myChallengePositionName . " Champion in the following list:<br>" . implode( ", ", $myRandChampions );

    $wgCaptchaQuestions[] = array( 'question' => $myChallengeQuestion, 'answer' => $myRandChampions[$myChallengeIndex] );


- name: Gadgets
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Gadgets.git
  version: "{{ mediawiki_default_branch }}"
- name: MobileFrontend
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/MobileFrontend.git
  version: "{{ mediawiki_default_branch }}"
  config: |
    $wgMFAutodetectMobileView = true;
- name: MsUpload
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/MsUpload.git
  version: "{{ mediawiki_default_branch }}"
  config: |
    $wgMSU_showAutoCat = true; // If true, files uploaded while editing a category will be added to that category
    $wgMSU_checkAutoCat = true; // Whether the checkbox for the above mentioned case is checked by default
    $wgMSU_imgParams = '400px'; // The default parameters for inserted images
    $wgMSU_useDragDrop = true; // Should the drag & drop area be shown?
    $wgMSU_useMsLinks = false; // Should we allow to insert links in the style of the Extension:MsLinks?
- name: Nuke
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Nuke.git
  version: "{{ mediawiki_default_branch }}"
- name: Renameuser
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Renameuser.git
  version: "{{ mediawiki_default_branch }}"

#
# Extensions loaded with legacy require_once method
#
- name: AntiBot
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/AntiBot.git
  version: "{{ mediawiki_default_branch }}"
  legacy_load: True
- name: CreateRedirect
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/CreateRedirect.git
  version: "{{ mediawiki_default_branch }}"
  legacy_load: True
# possible widget? or just don't do it? or download the code manually
# - name: FollowButton
#   https://www.mediawiki.org/wiki/Extension:FollowButton
- name: Loops
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Loops.git
  version: "{{ mediawiki_default_branch }}"
  legacy_load: True
  config: |
    ExtLoops::$maxLoops = 5000;
- name: MagicNoCache
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/MagicNoCache.git
  version: "{{ mediawiki_default_branch }}"
  legacy_load: True
- name: MyVariables
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/MyVariables.git
  version: "{{ mediawiki_default_branch }}"
  legacy_load: True
# unmaintained. May be problematic
- name: NoTitle
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/NoTitle.git
  version: "{{ mediawiki_default_branch }}"
  legacy_load: True
- name: OpenGraphMeta
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/OpenGraphMeta.git
  version: "{{ mediawiki_default_branch }}"
  legacy_load: True
- name: SwiftMailer
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/SwiftMailer.git
  version: "{{ mediawiki_default_branch }}"
  legacy_load: True
  config: |
    $wgSMTP = array(
      'host'     => "smtp.gmail.com",
      'IDHost'   => "gmail.com",
      'port'     => 465,
      'auth'     => true,
      'username' => "admin@esportspedia.com",
      'password' => "gde298DC@mNo"
    );
# need to use widgets instead
# - name: TwitterFBLike
#   repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/TwitterFBLike.git
#   version: "{{ mediawiki_default_branch }}"
#   legacy_load: True
- name: Widgets
  repo: https://gerrit.wikimedia.org/r/p/mediawiki/extensions/Widgets.git
  version: "{{ mediawiki_default_branch }}"
  legacy_load: True
  # this module requires a git submodule update --init; thus the next line
  git_submodules: True

#
# libraries loaded by composer
#
- name: DataValues
  #repo: https://github.com/DataValues/DataValues.git
  composer: "data-values/data-values"
  version: "~1.0"
- name: DataValuesCommon
  composer: "data-values/common"
  version: "0.3.*"
- name: DataValuesGeo
  composer: "data-values/geo"
  version: "1.2.*"
- name: DataValuesInterfaces
  composer: "data-values/interfaces"
  version: "0.2.*"
- name: DataValuesTime
  composer: "data-values/time"
  version: "0.8.*"
- name: DataValuesValidators
  composer: "data-values/validators"
  version: "0.1.*"
- name: ParserHooks
  composer: mediawiki/parser-hooks
  version: "~1.5"
- name: WikiSEO
  # repo: https://github.com/tinymighty/wiki-seo.git WikiSEO
  composer: tinymighty/wiki-seo
  version: "~1.2"

